Dyg.Admin/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dyg.Core.Data;
using Dyg.Core.Model;
using Dyg.Admin.Models;

namespace Dyg.Admin.Controllers
{
    public class BrandsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BrandsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Brands
        public IActionResult Index()
        {
            Security.LoginCheck(HttpContext);
            var category = _context.Brands.Include(b => b.BrandCategories).ThenInclude(bc => bc.Category).OrderBy(b=>b.Name).ToList();
            ViewBag.Categories = category;

            //var brands = (from e in _context.Brands
            //              join b in _context.BrandCategories on e.Id equals b.BrandId
            //              join c in _context.Categories on b.CategoryId equals c.Id
            //              select new Brand { CategoryId = c.Id });
            //ViewBag.Brands = brands;

            
            //var result = (
            //// instance from context
            //from a in _context.Brands
            //    // instance from navigation property
            //from b in a.BrandCategories
            //from c in b.CategoryId
            //    //join to bring useful data
            //join d in _context.Categories on b.CategoryId equals d.Id
            
            //select new CategoryViewModel
            //{
               
            //    Name = d.Name
            //}).ToList();

            //ViewBag.Result = result;
            return View(category);

           

        }


        // GET: Brands/Details/5
        public async Task<IActionResult> Details(string id)
        {
            Security.LoginCheck(HttpContext);
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .SingleOrDefaultAsync(m => m.Id == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // GET: Brands/Create
        public IActionResult Create()
        {

            Security.LoginCheck(HttpContext);
            Brand b = new Brand();

            b.CreateDate = DateTime.Now;
            b.CreatedBy = User.Identity.Name;
            b.UpdateDate = DateTime.Now;
            b.UpdatedBy = User.Identity.Name;
            b.PublishDate = DateTime.Now;

            var category = _context.Categories.Where(n => n.ParentCategoryId == null).OrderBy(o => o.Name).ToList(); ;
            ViewBag.Categories = category;
            return View(b);

        }
        // POST: Brands/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,CreateDate,CreatedBy,PublishDate,IsPublished,UpdateDate,UpdatedBy")] Brand brand)
        {
            Security.LoginCheck(HttpContext);
            if (ModelState.IsValid)
            {
                brand.CreateDate = DateTime.Now;
                brand.CreatedBy = User.Identity.Name;
                brand.UpdateDate = DateTime.Now;
                brand.UpdatedBy = User.Identity.Name;
                brand.PublishDate = DateTime.Now;

                var category = _context.Categories.Where(n => n.ParentCategoryId == null).OrderBy(o => o.Name).ToList(); ;
                ViewBag.Categories = category;

                _context.Add(brand);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Brands/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            Security.LoginCheck(HttpContext);
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands.SingleOrDefaultAsync(m => m.Id == id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        // POST: Brands/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,CreateDate,CreatedBy,PublishDate,IsPublished,UpdateDate,UpdatedBy")] Brand brand)
        {
            Security.LoginCheck(HttpContext);
            if (id != brand.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    brand.UpdateDate = DateTime.Now;
                    brand.UpdatedBy = User.Identity.Name;

                    _context.Update(brand);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Brands/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            Security.LoginCheck(HttpContext);
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .SingleOrDefaultAsync(m => m.Id == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            Security.LoginCheck(HttpContext);
            var brand = await _context.Brands.SingleOrDefaultAsync(m => m.Id == id);
            _context.Brands.Remove(brand);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BrandExists(string id)
        {
            return _context.Brands.Any(e => e.Id == id);
        }
    }
}

Dyg.Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dyg.Core.Data;
using Dyg.Core.Model;
using System.Security.Cryptography;
using System.Text;
using Dyg.Admin.Models;
using Microsoft.AspNetCore.Identity;
namespace Dyg.Admin.Controllers
{
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _context;
        //private readonly UserManager<Dyg.Core.Model.User> _userManager;

        public UsersController(ApplicationDbContext context)
        {
            _context = context;
            //_userManager = userManager;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            Security.LoginCheck(HttpContext);
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(string id)
        {
            Security.LoginCheck(HttpContext);
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .SingleOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }
        
        // GET: Users/Create
        public IActionResult Create()
        {
            //Security.LoginCheck(HttpContext);
            User user = new User();
            user.CreateDate = DateTime.Now;
            user.CreatedBy = User.Identity.Name;
            user.UpdateDate = DateTime.Now;
            user.UpdatedBy = User.Identity.Name;
            return View(user);
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Email,Password,ConfirmPassword,CreateDate,CreatedBy,UpdateDate,UpdatedBy")] User user)
        {
            //Security.LoginCheck(HttpContext);
            if (ModelState.IsValid)
            {
                user.CreateDate = DateTime.Now;
                user.CreatedBy = User.Identity.Name;
                user.UpdateDate = DateTime.Now;
                user.UpdatedBy = User.Identity.Name;
                user.Password = Convert.ToBase64String(SHA256.Create().ComputeHash(Encoding.UTF8.GetBytes(user.Password)));
                try
                {
                    _context.Add(user);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    // herhangi bir hata olursa burası çalışır
                    ModelState.AddModelError("Email", "Bu e-posta adresi daha önce kullanılmış.");
                }
              
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            Security.LoginCheck(HttpContext);

            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Email,Password,ConfirmPassword,CreateDate,CreatedBy,UpdateDate,UpdatedBy")] User user)
        {
            Security.LoginCheck(HttpContext);
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try {
                    user.UpdateDate = DateTime.Now;
                    user.UpdatedBy = User.Identity.Name;
                    user.Password = Convert.ToBase64String(SHA256.Create().ComputeHash(Encoding.UTF8.GetBytes(user.Password)));
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            Security.LoginCheck(HttpContext);
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .SingleOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            Security.LoginCheck(HttpContext);
            var user = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(string id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

Dyg.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Admin</title>
        <!-- Bootstrap Core CSS -->

        <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

        <!-- MetisMenu CSS -->
        <link href="~/vendor/metisMenu/metisMenu.min.css" rel="stylesheet" />
        <!-- Custom CSS -->
        <link href="~/dist/css/sb-admin-2.css" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <!-- Morris Charts CSS -->
        <link href="~/vendor/morrisjs/morris.css" rel="stylesheet">
      

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->


        <!-- jQuery -->
        <script src="~/vendor/jquery/jquery.min.js"></script>
        <!-- Bootstrap Core JavaScript -->
        <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
        <!-- Metis Menu Plugin JavaScript -->
        <script src="~/vendor/metisMenu/metisMenu.min.js"></script>
        <!-- Morris Charts JavaScript -->
        <script src="~/vendor/raphael/raphael.min.js"></script>
        <script src="~/vendor/morrisjs/morris.min.js"></script>
        <script src="~/data/morris-data.js"></script>
        <!-- Custom Theme JavaScript -->
        <script src="~/dist/js/sb-admin-2.js"></script>
    </head>

    <body style="background:url('/images/background.png') no-repeat;background-size:cover;">
       
        @RenderBody()
       
        <footer>
            <p>&copy; 2017 - Dyg.Admin</p>
        </footer>
    

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("Scripts", required: false)
    </body>
</html>

Dyg.Admin/Views/Shared/_Layout2.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Admin</title>
    <!-- Bootstrap Core CSS -->

    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

    <!-- MetisMenu CSS -->
    <link href="~/vendor/metisMenu/metisMenu.min.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- Morris Charts CSS -->
    <link href="~/vendor/morrisjs/morris.css" rel="stylesheet">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery -->
   
</head>

<body>

    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0; background-color:deepskyblue;" >
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-controller="Home" asp-action="Index" style="color:darkred"><b>DYG</b></a>
                
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-right" >
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Read All Messages</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-messages -->
                </li>
                <!-- /.dropdown -->
                
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-comment fa-fw"></i> New Comment
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="pull-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> Message Sent
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-tasks fa-fw"></i> New Task
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i><i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a asp-controller="Home" asp-action="Login"><i class="fa fa-sign-out fa-fw"></i>Çıkış</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->
            <!-- /.navbar-top-links -->
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <div class="navbar-default sidebar" role="navigation" >
                            <div class="sidebar-nav navbar-collapse">
                                <ul class="nav" id="side-menu">

                                    <li>
                                        <a asp-controller="Products" asp-action="Index"><i class="fa fa-dashboard fa-fw"></i>Ürünler</a>
                                    </li>
                                    <li>
                                        <a asp-controller="Brands" asp-action="Index"><i class="fa fa-dashboard fa-fw"></i>Markalar</a>
                                        <!-- /.nav-second-level -->
                                    </li>
                                    <li>
                                        <a asp-controller="Categories" asp-action="Index"><i class="fa fa-table fa-fw"></i>Kategoriler</a>

                                    </li>
                                    <li>
                                        <a asp-controller="Users" asp-action="Index"><i class="fa fa-user fa-fw"></i>Kullanıcılar</a>

                                    </li>
                                       <li>
                                        <a href="#"><i class="fa fa-edit fa-fw"></i>Formlar<span class="fa arrow"></span></a>
                                        <ul class="nav nav-second-level">
                                            <li>
                                                <a asp-controller="Categories" asp-action="Create">Kategori Ekle</a>
                                            </li>
                                            <li>
                                                <a asp-controller="Brands" asp-action="Create">Marka Ekle</a>
                                            </li>
                                            <li>
                                                <a asp-controller="Products" asp-action="Create">Ürün Ekle</a>
                                            </li>

                                        </ul>
                                      </li>
                                  
                                </ul>
                            </div>
                            </div>
                            <!-- /.sidebar-collapse -->

                     

                        </ul>
                    </div>
                </div>
            

        </nav>
    </div>
    <div>
        @RenderBody()

    </div>

    <footer>
        <p>&copy; 2017 - Dyg.Admin</p>
    </footer>

    <script src="~/vendor/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/vendor/metisMenu/metisMenu.min.js"></script>
    <!-- Morris Charts JavaScript -->
    <script src="~/vendor/raphael/raphael.min.js"></script>
    <script src="~/vendor/morrisjs/morris.min.js"></script>
    <script src="~/data/morris-data.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="~/dist/js/sb-admin-2.js"></script>
    <!-- DataTables JavaScript -->
    <script src="~/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="~/vendor/datatables-responsive/dataTables.responsive.js"></script>


    @RenderSection("Scripts", required: false)
</body>


</html>